version: "3.7"

services:
  web:
    build: .
    environment:
      - REDIS_URL=redis://localhost:6379/0
    volumes:
      - .:/app
    links:
      - redis
    ports:
      - "4000:4000"
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rake db:migrate && bundle exec rails s -p 4000 -b '0.0.0.0'"
    network_mode: "host"
  sidekiq:
    build: .
    volumes:
      - .:/app
    links:
      - redis
    command: sidekiq -C config/sidekiq.yml
    network_mode: "host"

  redis:
    image: redis
    network_mode: "host"
