version: "3.7"

services:
  web:
    build: .
    environment:
      - REDIS_URL=redis://redis:6379/0
    volumes:
      - .:/app
    links:
      - redis
    ports:
      - "3000:3000"
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rake db:migrate && bundle exec rails s -p 3000 -b '0.0.0.0'"

  sidekiq:
    build: .
    volumes:
      - .:/app
    links:
      - redis
    command: sidekiq -C config/sidekiq.yml

  redis:
    image: redis
